echo "Installing from $AI_STACK_DIR"

# Ensure Root
if [ "$EUID" -ne 0 ]; then
  echo "Run as root (su)"
  exit 1
fi

# Install Ollama
curl -fsSL https://ollama.com/install.sh | sh

# Add Ollama User
if ! id ollama >/dev/null 2>&1; then
    useradd -r -s /bin/false -U -m -d /usr/share/ollama ollama
fi
usermod -a -G ollama $(whoami)

read -p "Context Length [4096]: " CONTEXT_LENGTH
CONTEXT_LENGTH=${CONTEXT_LENGTH:-4096}

read -p "Ollama Model Save Location [/usr/share/ollama/.ollama/models]: " OLLAMA_MODELS
OLLAMA_MODELS=${OLLAMA_MODELS:-/usr/share/ollama/.ollama/models}

# Make sure model directory exists
mkdir -p "$OLLAMA_MODELS"
chown -R ollama:ollama /usr/share/ollama

# Find Ollama
OLLAMA_LOCATION=$(command -v ollama)

if [ -z "$OLLAMA_LOCATION" ]; then
    echo "Ollama executable not found"
    exit 1
fi

# Create SystemD Service
cat > "/etc/systemd/system/ollama.service" <<EOF
# Auto-generated by setup
[Unit]
Description=Ollama Service
After=network-online.target

[Service]
ExecStart=$OLLAMA_LOCATION serve
User=ollama
Group=ollama
Restart=always
RestartSec=3
Environment="PATH=$PATH"
Environment="OLLAMA_MODELS=$OLLAMA_MODELS"
Environment="OLLAMA_CONTEXT_LENGTH=$CONTEXT_LENGTH"

[Install]
WantedBy=multi-user.target
EOF

# Start Service
systemctl daemon-reload
systemctl enable ollama
systemctl start ollama